# Generated by Django 6.0.3 on 2026-05-01 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaacademica',
            name='alumno',
        ),
        migrations.RemoveField(
            model_name='notaacademica',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='alumno_asignado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='puntos_acumulados',
        ),
        migrations.DeleteModel(
            name='CanjeoRecompensa',
        ),
        migrations.DeleteModel(
            name='Recompensa',
        ),
        migrations.DeleteModel(
            name='NotaAcademica',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
    ]
