"""
Django settings for CJRewards project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Carga las variables de entorno desde el archivo .env o .env.local
load_dotenv(Path(__file__).resolve().parent.parent / '.env.local')

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Obtiene la clave del archivo .env.local, si no existe lanza un error
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-fallback-clave-temporal')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Lee los dominios permitidos desde el entorno (separados por comas)
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')

# Para evitar el error 400 Bad Request en Vercel, permitimos automáticamente todos los subdominios de vercel
if '.vercel.app' not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append('.vercel.app')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Aplicación de CJ Rewards
    'core',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WHITENOISE: Middleware especializado para interceptar, empaquetar y servir 
    # los archivos estáticos (CSS de Tailwind, imágenes) en un entorno Serverless sin necesitar Nginx
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'core.auth_backend.FirebaseBackend', # Backend híbrido Firebase-SQLite
    'django.contrib.auth.backends.ModelBackend', # Backend nativo
]

ROOT_URLCONF = 'CJRewards.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'core', 'templates')], 
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CJRewards.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

import os
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'core', 'static'),
]

AUTH_USER_MODEL = 'core.Usuario'

LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# CAMBIO CRÍTICO PARA SERVERLESS (Manejo de Sesiones sin Base de Datos local)
# En lugar de guardar el login en el archivo SQLite (que Vercel bloquea), 
# se guarda el ticket de sesión directamente en el navegador del usuario usando criptografía
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"

# =======================================================
# POLÍTICAS ESTRICTAS PARA ENTORNO DE PRODUCCIÓN
# =======================================================
if not DEBUG:
    # Obliga al navegador a comunicarse siempre por canales encriptados HTTPS
    SECURE_SSL_REDIRECT = True
    # Impide que las cookies puedan ser robadas en conexiones de Wi-Fi públicas
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Obliga al navegador a recordar que la web solo admite HTTPS (HSTS)
    SECURE_HSTS_SECONDS = 31536000

# =======================================================
# PROTECCIÓN ANTI FUERZA BRUTA (Sustituto de Axes para Vercel)
# =======================================================
# La protección se gestiona en gestor_firebase.py mediante comprobar_rate_limit,
# evitando escrituras en el sistema de archivos de solo lectura de Vercel.

